config/routes.rb
Rails.application.routes.draw do
  scope module: :app, as: 'app', constraints: { subdomain: 'roundabout' } do
    root 'home#index'
  end

  match "*unmatched_route", to: 'link#show', via: :all
  root to: "link#show", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/controllers/app/home_controller.rb
module App
  class HomeController < ApplicationController
    def index
      @stats = OpenStruct.new(
        links: Link.count,
        accesses: 0,
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  def show
    short_url = "#{request.host}#{request.path}"
    link = Link.find_by(short_url: short_url)

    redirect_to link.long_url, status: 302 if link.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/home/index.html.erb
<h1>Roundabout</h1>
<h2 class="text-muted">Custom and short links</h2>

<hr />

<ul>
  <li>
    <strong>Links:</strong>
    <%= @stats.links %>
  </li>

  <li>
    <strong>Accesses:</strong>
    <%= @stats.accesses %>
  </li>
</ul>

<hr />

<a href="https://evandro.sasse.it">by evsasse</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roundabout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container my-1">
      <%= yield %>
    </div>
  </body>
</html>

app/views/link/show.html.erb
<div class="text-center my-5">
  <h1 class="display-1">404</h1>
  <h2 class="text-muted">Roundabout not found</h2>
  <%= link_to app_root_url, class: 'text-muted small mt-5' do %>
    Roundabout?
  <% end %>
</div>